version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports: [ "8000:8000" ]
  frontend:
    build: ./frontend
    depends_on: [ backend ]
    ports: [ "3000:80" ]
    environment:
      - VITE_API_URL=/api     # nginx reverse-proxy rule
